package ethos.runehub.content.journey;

public enum JourneyStepType {

    COLLECTION,DEPLETION,TASK,CHALLENGE,DIALOG,NPC_TELEPORT_ACTION,CAST_SPELL,CONSUME_ITEM,OPEN_SHOP,BUY_ANY_FROM_SHOP,SELL_ANY_TO_SHOP,BUY_ID_FROM_SHOP,SELL_ID_TO_SHOP,EQUIP_ID,NODE_INTERACTION,SKILL_EVENT_FROM_ID
}
