package ethos.model.content.achievement;

/**
 * 
 * @author Jason http://www.rune-server.org/members/jason
 * @date Mar 27, 2014
 */
public enum AchievementType {

	/*
	 * PVM
	 */
	SLAY_ROCK_CRABS, SLAY_COWS, SLAY_CHAOS_DRUIDS, SLAY_CHICKENS, SLAY_ANY_NPCS, SLAY_BABY_DRAGONS, SLAY_DRAGONS, SLAY_BOSSES,
	KBD_DESTROYER, MASTER_ELF, HILL_GIANT_SLAYER, SLAY_SMOKE_DEVILS, SLAY_DEMONIC_GORILLA, SLAY_BARREL_CHEST, SLAY_GIANT_MOLE,
	MAD_SCIENTIST, CHAOS_FANATIC, VENENATIS, VETION, KRAKEN, ZULRAH, LIZARD_SHAMAN, MITHRIL_DRAGON,

	/*
	 * Skill
	 */
	FISH, COOK, MINE, SMITH, FARM, HERB, WOODCUT, FLETCH, FIRE, THIEV, AGIL, ROOFTOP, SLAY, RUNECRAFTING,HUNTER,PRAYER,MAGIC,

	/*
	 * Complete minigames/Crystal chest
	 */
	// Tier 1
	LOOT_CRYSTAL_CHEST, PEST_CONTROL_ROUNDS, FIGHT_CAVES_ROUNDS, BARROWS_RUNS,

	/*
	 * Others
	 */
	CLUES,

}
